<?php

echo $title;

?>


<br>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>

<br>
<br>
<form action="/user/register" method="post" enctype="multipart/form-data">
    Login: <input type="text" name="name" value=""><br>
    Password: <input type="text" name="password" value=""><br>
    Email: <input type="text" name="email" value=""><br>
    Date of Birth: <input type="date" name="birth_date" value=""><br>
    <input type="submit" value="register">
</form>
<br>
<br>
<?php
if ($title):
?>
<?php echo "And now you need to authorized" ?>
<?php endif; ?>
<br>
<br>
<br>
<form action="/user/authorize" method="post">
    Login: <input type="text" name="name" value=""><br>
    Password: <input type="text" name="password" value=""><br>
    <!--    email:  <input type="text" name="email" value=""><br>-->
    <input type="submit" value="auth">
</form>
</body>
</html>

<br>